### ISSUE TITLE
There is no dist version of this package

### ISSUE THREAD

**Issue by geekplux** [rubenspgcavalcante/leaflet-ant-path#13]
There is no dist version of this package installed by npm or downloaded from GitHub...
so that I have to run `gulp pack` by myself.

Thank your nice code but please release a dist. Thanks

**Comment by rubenspgcavalcante** [comment]
Strange, here after the npm install, the build task 'pack' has been triggered and after that, the dist is outputed. If you download directly you will need to build, because this repository is based to be a npm module, and the build is made after 'npm install' (differently from bower, and which you can download [here](https://github.com/rubenspgcavalcante/leaflet-ant-path-bower)).

Can you paste the output after you do a 'npm install leaflet-ant-path'?

**Comment by geekplux** [comment]
using the `cnpm` instand of `npm` just because of GFW of China...so this might be the key to problem?

<img width="618" alt="screen shot 2016-08-01 at 22 27 26" src="https://cloud.githubusercontent.com/assets/3816105/17297204/4afd19ae-5837-11e6-9ca8-827ad80a4b80.png">

**Comment by rubenspgcavalcante** [comment]
Probably yes. The common behavior of a npm module is to run command declared in the "scripts.install" property of package.json. Can you confirm this with the cnpm team? I'll close this issue for now, but if isn't a problem of cnpm itself, I can open again.

![install-ouput](https://cloud.githubusercontent.com/assets/739913/17301756/1439cfea-57ef-11e6-88a5-375bcdb8509a.png)

**Comment by geekplux** [comment]
thanks!

**Comment by geekplux** [comment]
fixed. thanks again.
