### ISSUE TITLE
AntPath not working on Cordova

### ISSUE THREAD

**Issue by erniomaldo** [rubenspgcavalcante/leaflet-ant-path#29]
Hi there, i have a problem with this awesome plugin, my problem show in the debugg app of monaca for android.

In the Monaca Cloud IDE the plugin works fine as you can see in this image: [https://drive.google.com/open?id=0B3tg8rd1hJTcT0ViQ012dzJBX2c](url)

But the problem is in the debugg app for android, you can see that in this image: [https://drive.google.com/open?id=0B3tg8rd1hJTcOXNHVk9yQjN6Vk0](url)

In the App Log you can see this error: [https://drive.google.com/open?id=0B3tg8rd1hJTcdGljUkI2Y1lzUHM](url)

I don't know what im doing wrong because the plugin works fine in the Cloud IDE, can you help me?

**Comment by rubenspgcavalcante** [comment]
Hi @erniomaldo ,
It seems a incompatibility on the android webview with the Reflection API from ES6.
I've just explicitly added the polyfill to it (because it was already included inside the Symbols API polyfill that I use, but was enclosed only in that scope).
Can you just clone the "dev" branch, build a version of it in your machine and use the built code to see if it works? (probably will)
If is all ok, I'll create a patch for this issue and release a new version in npm and bower.

**Comment by rubenspgcavalcante** [comment]
If you have some difuculties, you can find the details here
https://github.com/rubenspgcavalcante/leaflet-ant-path/blob/dev/.github/contributing.md#testing-and-building

**TL;TR;** Basically to build the project, you will clone or even download the code and inside the root directory run the command:
```
npm install
npm run build
```

The last command will build and output the plugin inside the "dist" directory. You can then just copy and paste it into your project and test if it works.

**Comment by erniomaldo** [comment]
Hi there, i can´t make de dist folder with the provided intructions, the console drop me this:

![help](https://cloud.githubusercontent.com/assets/26859702/25010715/8d503036-2030-11e7-9ea2-d80cd6a3ea7f.png)

The log file related is:
[https://drive.google.com/open?id=0B3tg8rd1hJTceFlzSE5KMmR5Xzg](https://drive.google.com/open?id=0B3tg8rd1hJTceFlzSE5KMmR5Xzg)

I think this can be because im doing something wrong, thanks.

**Comment by rubenspgcavalcante** [comment]
It's complaining about two things:
- It can't find phantomjs on the $PATH variable
- It does not recognize $NODE_ENV as a variable

The problem is because the windows "cmd" does not recognize the "bash" things. So, do you have some environment that simulates the Linux bash (like cygwin) or a linux machine available? (can even be a docker container, so you can run the build process there)

In future versions I'll let a Dockerfile available so you can run the build in a very simple way in any platform, but in the moment can you do it by yourself? (sorry about that)

**Comment by erniomaldo** [comment]
No problem, i can figure out with linux, thanks for the help.

**Comment by erniomaldo** [comment]
Hi, i just set up my antpath compile enviroment, after trying to get the dist folder i get no errors and then i upload the news files to monaca, but the problem resist to get solved, im not uploading any file because the error is the same(letter by letter) in the reported issue, how can i help you to debug the error?

**Comment by rubenspgcavalcante** [comment]
Ok, so I'll try to run the project over the cordova and run in a mobile. Can you say which version of webview you're using? Is only in Android or it happens in IOS also?

**Comment by erniomaldo** [comment]
Grettings Ruben, i'm using the native webview(5.1) component of the SO Android, by the moment i only have android devices, let me try to run on a IOS phone, the version of cordova is:

![image](https://cloud.githubusercontent.com/assets/26859702/25272170/83234946-264c-11e7-9dfc-bf2899b76c8e.png)

I hope this info can help.

**Comment by erniomaldo** [comment]
Hi there, about testing in IOS, i can't do this right now because i don't have the Apple Developer Program(99USD), this is necesary to build/debug in IOS, i will purchase that when i get the resources for that, sorry.

**Comment by rubenspgcavalcante** [comment]
No worries @erniomaldo!
So, I'll try to get some time and mount a cordova project with the same version of yours and try to debug it. :)
