### ISSUE TITLE
Amination speed varies with map width

### ISSUE THREAD

**Issue by webalchemist** [rubenspgcavalcante/leaflet-ant-path#63]
**Type:**
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] question

**Environment:**
 - OS: Windows 10
 - Browser: Chrome
 - Library Version: 1.1.2

**I'm going to open a PR:**
- [ ] yes
- [x] no

**Description:**
The animation speed varies with the width of the map.  Is this supposed to happen?
If you change the browser width on your example page you can see this effect.

**Comment by rubenspgcavalcante** [comment]
Hi @webalchemist , the thing is the viewport. Leaflet "clips" the vectors, changing their final size.
So if you have a very horizontal antPath that goes out of the map's viewport, leaflet will cut it and the CSS animation will be affected by this clipping (that's why if the map viewport is larger the speed changes)
Unfortunately I still didn't find a way to check a solution for that, the best I can do is a calculation using the map zoom and the delay wanted.

Although, when having time I'm going to research a way to setup the css animation on this shorter/clipped vector considering the viewport and the final size displayed.
